SalesforceCode/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>TimeStamp__c</fullName>
        <description>When the event was recorded.</description>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceCode/objects/EventAttribute__c.object
<CustomObject>
    <description>Stores a key-value pair containing data about a Salsalytics Event</description>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentEvent__c</fullName>
        <label>ParentEvent</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>EventAttributes</relationshipLabel>
        <relationshipName>EventAttributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EventAttribute</label>
    <nameField>
        <label>EventAttribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventAttributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceCode/objects/Graph__c.object
<CustomObject>
    <description>Custom Object to store data about a Graph that  the user can create. Will contain objects such as graph type, filters, axes(?), and the query required to get the data from the database.</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <description>Graph attribute that is to be graphed</description>
        <label>Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChartType__c</fullName>
        <label>ChartType</label>
        <picklist>
            <picklistValues>
                <fullName>bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>timeline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <description>Stores the query that will be used to get the data from the database.</description>
        <label>Query</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Graph</label>
    <nameField>
        <label>Graph Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Graphs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceCode/classes/SingleGraphControllerTest.cls
@isTest
public class SingleGraphControllerTest
{
    static testMethod void testDeleteGraph()
    {
        Graph__c g = new Graph__c();
        g.Query__c = 'select asdf';
        insert g;
        SingleGraphController.deleteGraph('' + g.ID);
        String query = 'SELECT Id from Graph__c where Id = \'' + g.ID + '\' LIMIT 1';
        System.assert(Database.query(query).isEmpty());
    }
    
    static testMethod void testGetGraph()
    {
        SingleGraphController controller = new SingleGraphController();
        
        // Create and insert dummy event with key/value pair
        Event__c e = new Event__c();
        e.name = 'testevent';
        e.timestamp__c = datetime.now();
        insert e;
        
        EventAttribute__c ea = new EventAttribute__c();
        ea.key__c = 'testkey';
        ea.value__c = 'testvalue';
        ea.ParentEvent__c = e.id;
        insert ea;
        
        // Create and insert graph object that queries on that pair
        Graph__c g = new Graph__c();
        g.query__c = 'SELECT Value__c, count(Key__c) FROM EventAttribute__c where Key__c = \'' + ea.key__c + '\' group by Value__c';
        g.name = 'testgraph1';
        g.attribute__c = ea.key__c;
        g.charttype__c = 'pie';
        insert g;
        
        // Create fake page environment since getGraph accesses query string!
        ApexPages.currentPage().getParameters().put('graphid', g.id);
        
        // Check that output graph string has the important stuff in it
        String chartString = controller.getGraph();
        System.assert(chartString.contains('testvalue'));
        System.assert(chartString.contains('1'));
        System.assert(chartString.contains('testgraph1'));
        System.assert(chartString.contains('pie'));
    }
}