SalesforceCode/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>TimeStamp__c</fullName>
        <description>When the event was recorded.</description>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceCode/objects/EventAttribute__c.object
<CustomObject>
    <description>Stores a key-value pair containing data about a Salsalytics Event</description>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EventAttribute</label>
    <nameField>
        <label>EventAttribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventAttributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceCode/objects/Graph__c.object
<CustomObject>
    <description>Custom Object to store data about a Graph that  the user can create. Will contain objects such as graph type, filters, axes(?), and the query required to get the data from the database.</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <description>Graph attribute that is to be graphed</description>
        <label>Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChartType__c</fullName>
        <label>ChartType</label>
        <picklist>
            <picklistValues>
                <fullName>bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>timeline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <description>Stores the query that will be used to get the data from the database.</description>
        <label>Query</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>DateTime</type>
    </fields>
    <label>Graph</label>
    <nameField>
        <label>Graph Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Graphs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceCode/classes/GraphAdder2.cls
global with sharing class GraphAdder2
{
    Graph__c newGraph = new Graph__c();
    ApexPages.StandardController stdController;
    
    global GraphAdder2.GraphAdder2(ApexPages.StandardController controller)
    {
        stdController = controller;
    }
    global void init() {
        
        newGraph.name = 'Hello';
        newGraph.chartType__c = 'pie';
        newGraph.attribute__c = 'hi';
        newGraph.query__c = 'SELECT Value__c, count(Key__c) FROM EventAttribute__c where Key__c = \'' + 
            newGraph.Attribute__c + '\' group by Value__c';
    }
    global void setQuery() {
        newGraph.Query__c = 'SELECT Value__c, count(Key__c) FROM EventAttribute__c where Key__c = \'' + newGraph.Attribute__c + '\' AND parentid in ' + 
        '(select ID from Event__c where TimeStamp__c > ' + newGraph.startDate__c + ' AND TimeStamp__c < ' + newGraph.endDate__c + ') group by Value__c';
    }
    global Graph__c getGraph()
    {
        init();
        return newGraph;
    }
    global void save()
    {
        setQuery();
        upsert(newGraph);
    }
    
    public Set<SelectOption> getAttributes()
    {
      Set<SelectOption> options = new Set<SelectOption>();
            
      // GET ATTRIBUTES SOQL
       List<EventAttribute__c> attributes = [select key__c, value__c from eventAttribute__c];
       
       
       for(EventAttribute__c attributeName : attributes)
       {
          options.add(new SelectOption(attributeName.key__c, attributeName.key__c));
       }       
       return options;
    }

}