SalesforceCode/objects/EventAttribute__c.object
<CustomObject>
    <description>Stores a key-value pair containing data about a Salsalytics Event</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EventAttribute</label>
    <nameField>
        <label>EventAttribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventAttributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceCode/objects/Graph__c.object
<CustomObject>
    <description>Custom Object to store data about a Graph that  the user can create. Will contain objects such as graph type, filters, axes(?), and the query required to get the data from the database.</description>
    <fields>
        <fullName>ChartType__c</fullName>
        <label>ChartType</label>
        <picklist>
            <picklistValues>
                <fullName>bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>timeline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <description>Stores the query that will be used to get the data from the database.</description>
        <label>Query</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Graph</label>
    <nameField>
        <label>Graph Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Graphs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceCode/classes/LessSimpleDynamicController.cls
public class LessSimpleDynamicController {
    Component.Apex.Chart chart;
    Integer count;
    Integer numGraphs, current;
    String chartString;
        
     public String getSomeChart() {
        chartString = '';
        count = 0;
        
        List<Graph__c> queries = getQueries();
        for (Graph__c g : queries) {
            // Create a graph based on this query
            chartString += '<div id="chart" class="chart" ';
            
            String graphName = g.Name;
            String chartType = g.chartType__c;
            chartString += 'graphName="' + graphName + '"';
            
            // Get the slices of the pie graph
            List<AggregateResult> slices = Database.query(g.Query__c);
            
            // Get the (label, count) pairs by some means
            //  and iterate over them
            for (Integer i = 0; i < slices.size(); i++) {
                chartString += 'field' + i + '="' + slices[i].get('value__c') + '" ';
                chartString += 'value' + i + '='  + slices[i].get('expr0') + ' ';
            }
            
            //chartString += 'chartType="pie"></div>\n'; 
            chartString += 'chartType="' + chartType + '"> </div>';
            System.debug(chartType);
            count++; 
        }
       
        return chartString;
    }
    
    private List<Graph__c> getQueries() {
        return [SELECT Query__c, Name, ChartType__c FROM Graph__c LIMIT 500];
    }
    
    private List<EventAttribute__c> getAttributes(String query) {
        return Database.query(query);
    }


}