SalesforceCode/objects/Graph__c.object
<CustomObject>
    <description>Custom Object to store data about a Graph that  the user can create. Will contain objects such as graph type, filters, axes(?), and the query required to get the data from the database.</description>
    <fields>
        <fullName>VisualForce_Page__c</fullName>
        <defaultValue>&quot;salsaforcedashboard&quot;</defaultValue>
        <description>The visual force page to redirect to when this graph is selected (only the part after na9.salesforce.com/apex/....)</description>
        <label>VisualForcePage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Graph</label>
    <nameField>
        <label>Graph Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Graphs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceCode/classes/SalsalyticsMainController.cls
public with sharing class SalsalyticsMainController {
    integer numTabs = 2;
    Component.Apex.Chart chart;
    Component.Apex.pieSeries pie;
    Component.Apex.Legend legend;
    Component.Apex.barSeries bar;
    Component.Apex.Axis axis;
    
    
   public static List<Data> getData() {
      return EventGraphPrototype2.getChartData();
   }
    
    public Map<String, String> getGraphNames() {
        Map<String, String> stringList = new Map<String, String>();
        List<Graph__c> attributes = new List<Graph__c>();
        attributes = [select Name, VisualForce_Page__c from Graph__c];
        for (Graph__c attribute : attributes)
        {
           stringList.put(attribute.Name, attribute.VisualForce_Page__c);
        }
        return stringList;
    }
    
    public Boolean getRendered(){
        return true;
    }
    
    public Map<String, String> getGraphIDs() {
        Map<String, String> result = new Map<String, String>();
        List<Graph__c> graphs = [SELECT name,ID from Graph__c];
        for (Graph__c g : graphs) {
            result.put(g.Name, g.ID);
        }
        return result;
    }
}